- name: Include vars
  include_vars:
    file: vars/main.yml
    name: node

- name: Create docker_node directory
  file:
    path: "{{ user_home }}/docker/docker_node"
    owner: "{{ user_name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  template:
    src: ./Dockerfile.j2
    dest: "{{ user_home }}/docker/docker_node/Dockerfile"
    owner: "{{ user_name }}"
    group: docker
    mode: 0550

- name: Create sites-enabled directory
  file:
    path: "{{ user_home }}/docker/docker_node/etc/nginx/sites-enabled"
    owner: "{{ user_name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy site conf
  template:
    src: "./etc/nginx/sites-enabled/{{ domain }}.conf.j2"
    dest: "{{ user_home }}/docker/docker_node/etc/nginx/sites-enabled/{{ domain }}.conf"
    owner: "{{ user_name }}"
    group: docker
    mode: 0550

- name: Create node app directory
  file:
    path: "{{ node_app_dir }}"
    owner: "{{ user_name }}"
    group: docker
    mode: 0750
    state: directory