- name: Create docker_node directory
  file:
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: docker
    mode: 0750
    state: directory
  with_items:
    - "{{ user.home }}/docker/docker_node{{ dir.node_app }}"

- name: Copy Dockerfile
  template:
    src: ./Dockerfile.j2
    dest: "{{ user.home }}/docker/docker_node/Dockerfile"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create etc directories
  file:
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory
  with_items:
    - "{{ dir.shared.sites_enabled }}"
    - "{{ dir.shared.certs }}"
    - "{{ dir.shared.private }}"

- name: Copy site conf
  template:
    src: "./etc/nginx/sites-enabled/node.webdev.conf.j2"
    dest: "{{ dir.shared.sites_enabled }}/{{ domains.node_app }}.conf"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ dir.shared.private }}/{{ domains.node_app }}.key"
  notify:
    - Chown private

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{ dir.shared.private }}/{{ domains.node_app }}.csr"
    privatekey_path: "{{ dir.shared.private }}/{{ domains.node_app }}.key"
    common_name: "{{ domains.node_app }}"
  notify:
    - Chown private

- name: Create openssl certificate
  openssl_certificate:
    path: "{{ dir.shared.certs }}/{{ domains.node_app }}.crt"
    privatekey_path: "{{ dir.shared.private }}/{{ domains.node_app }}.key"
    csr_path: "{{ dir.shared.private }}/{{ domains.node_app }}.csr"
    provider: selfsigned
  notify:
    - Chown certs

- name: Create node app directory
  file:
    path: "{{ dir.node_app }}"
    owner: "{{ user.name }}"
    group: docker
    mode: 0750
    state: directory