FROM node:alpine3.11

USER root

RUN apk update
RUN apk add bash \
            python \
            python3 \
            curl \
            openssl \
            git \
            build-base \
            sudo

RUN addgroup --gid {{ user.gid }} {{ user.group }}
RUN adduser  {{ user.name }} --uid {{ user.uid }}  -G {{ user.group }} --disabled-password
RUN echo "{{ user.password }}:{{ user.password }}" | chpasswd

# --- Add user to sudoers
RUN echo "{{ user.name }} ALL=(ALL) ALL" > /etc/sudoers.d/{{ user.name }}
RUN chmod 0440 /etc/sudoers.d/{{ user.name }}
RUN echo "Set disable_coredump false" >> /etc/sudo.conf

RUN npm i -g pm2

WORKDIR {{ dir.node_app }}

COPY .{{ dir.node_app }}/package.json .
RUN npm install

RUN chown {{ user.name }}:{{ user.group }} ./node_modules
USER {{ user.name }}

EXPOSE 3000

CMD [ "pm2-runtime", "--name", "facebug", "npm", "--", "start" ]